name: Release
on:
    workflow_run:
        workflows: ["Tests"]
        branches: [main]
        types:
            - completed

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
            - name: Publish Package
              run: npm set-script prepare '' && npm install && npm run build && npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
