version: "3.8"

services:
  postgres:
    image: postgres:14.8
    hostname: postgres
    container_name: postgres
    networks:
      - promentor_net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - TIMESCALEDB_TELEMETRY=off
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./provision/postgres:/docker-entrypoint-initdb.d

  keycloak:
    depends_on:
      - postgres
    build:
      context: ./keycloak
    hostname: keycloak
    container_name: keycloak
    networks:
      - promentor_net
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT:-8080}:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=idp.promentor.local
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - DEBUG=true
    volumes:
      - ./provision/keycloak:/tmp/import
      # disable theam cache
      - ./keycloak/scripts/disable-theam-cache.cli:/opt/jboss/startup-scripts/disable-theam-cache.cli
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/tmp/import"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    networks:
      - promentor_net
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./provision/mongo:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3.12
    hostname: rabbitmq
    container_name: rabbitmq
    networks:
      - promentor_net
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/

networks:
  promentor_net:

volumes:
  db-data:
