# Generated by Django 4.2.11 on 2024-04-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_job_jobguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobguide',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='skills.job'),
        ),
    ]
