/**
 * Error codes for the application.
 * These error codes are used to identify the error application specific type.
 * @enum {string}
 */
enum ErrorCode {
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
    INVALID_URL = "INVALID_URL",
    INVALID_ARRAY = "INVALID_ARRAY",

    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    REQUEST_ORIGIN_NOT_FOUND = "REQUEST_ORIGIN_NOT_FOUND",

    USER_ALREADY_EXISTS_IN_DB = "USER_ALREADY_EXISTS_IN_DB",
    USER_NOT_FOUND_IN_KEYCLOAK = "USER_NOT_FOUND_IN_KEYCLOAK",
    USER_NOT_FOUND_IN_DB = "USER_NOT_FOUND_IN_DB",

    GROUP_NOT_FOUND = "GROUP_NOT_FOUND",
    TENANT_NOT_FOUND = "TENANT_NOT_FOUND",

    AWS_SES_ERROR = "AWS_SES_ERROR",

    IMAGE_PATH_NOT_FOUND = "IMAGE_PATH_NOT_FOUND",

    UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

    /** axios error codes */
    ERR_FR_TOO_MANY_REDIRECTS = "ERR_FR_TOO_MANY_REDIRECTS",
    ERR_BAD_OPTION_VALUE = "ERR_BAD_OPTION_VALUE",
    ERR_BAD_OPTION = "ERR_BAD_OPTION",
    ERR_NETWORK = "ERR_NETWORK",
    ERR_DEPRECATED = "ERR_DEPRECATED",
    ERR_BAD_RESPONSE = "ERR_BAD_RESPONSE",
    ERR_BAD_REQUEST = "ERR_BAD_REQUEST",
    ERR_NOT_SUPPORT = "ERR_NOT_SUPPORT",
    ERR_INVALID_URL = "ERR_INVALID_URL",
    ERR_CANCELED = "ERR_CANCELED",
    ECONNABORTED = "ECONNABORTED",
    ETIMEDOUT = "ETIMEDOUT",
}

export {
    ErrorCode
};
